version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - nginx_network
    environment:
      TZ: $VAR_TIMEZONE
    depends_on:
      - back
      - socket
  db:
    build:
      context: db
      dockerfile: Dockerfile
    networks:
      - nginx_network
    ports:
      - "3306:3306"
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: $VAR_TIMEZONE
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/db-datadir:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - nginx_network
  back:
    build:
      context: back
      dockerfile: Dockerfile
    volumes:
      - ./back/app:/app
    networks:
      - nginx_network
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "8001"
    links:
      - db
  socket:
    build:
      context: socket
      dockerfile: Dockerfile
    volumes:
      - ./socket/app:/app
    networks:
      - nginx_network
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "3001"
    links:
      - db
  front:
    build:
      context: front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    ports:
      - "8080:8080"
    tty: true

networks:
  nginx_network:
    driver: bridge